GCOV_PROFILE := y

ccflags-y := -Werror
obj-y := nvadsp.o
nvadsp-objs += dev.o os.o app.o app_loader_linker.o\
	 nvadsp_aram.o nvadsp_dram.o \
	 nvadsp_cmsg_queue.o \
	 nvadsp_shared_sema.o nvadsp_arb_sema.o \
	 hwmailbox.o mailbox.o ape_actmon.o
