#ifndef _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H
#define _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H 1

/* 0-15 for USB3 */
#define TEGRA_USB3_PADCTL_USB3_BASE	(0)
#define TEGRA_XUSB_PADCTL_USB3_P(x)	((x) + TEGRA_USB3_PADCTL_USB3_BASE)
/* 16-31 for UTMI */
#define TEGRA_USB3_PADCTL_UTMI_BASE	(16)
#define TEGRA_XUSB_PADCTL_UTMI_P(x)	((x) + TEGRA_USB3_PADCTL_UTMI_BASE)
/* 32-47 for HSIC */
#define TEGRA_USB3_PADCTL_HSIC_BASE	(32)
#define TEGRA_XUSB_PADCTL_HSIC_P(x)	((x) + TEGRA_USB3_PADCTL_HSIC_BASE)
/* 48-63 for PCIE */
#define TEGRA_USB3_PADCTL_PCIE_BASE	(48)
#define TEGRA_XUSB_PADCTL_PCIE_P(x)	((x) + TEGRA_USB3_PADCTL_PCIE_BASE)
/* 64-79 for SATA */
#define TEGRA_USB3_PADCTL_SATA_BASE	(64)
#define TEGRA_XUSB_PADCTL_SATA_P(x)	((x) + TEGRA_USB3_PADCTL_SATA_BASE)
/* 80-95 for UFS */
#define TEGRA_USB3_PADCTL_UFS_BASE	(80)
#define TEGRA_XUSB_PADCTL_UFS_P(x)	((x) + TEGRA_USB3_PADCTL_UFS_BASE)

#endif /* _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H */

