#ifndef __UAPI_CORESIGHT_STM_H_
#define __UAPI_CORESIGHT_STM_H_

enum {
	STM_ENTITY_NONE			= 0x00,
	STM_ENTITY_TRACE_PRINTK		= 0x01,
	STM_ENTITY_TRACE_USPACE		= 0x02,
	STM_ENTITY_MAX			= 0xFF,
};

enum {
	STM_IOCTL_NONE			= 0x00,
	STM_IOCTL_SET_OPTIONS		= 0x01,
	STM_IOCTL_GET_OPTIONS		= 0x10,
};

enum {
	STM_OPTION_NONE			= 0x0,
	STM_OPTION_TIMESTAMPED		= 0x08,
	STM_OPTION_GUARANTEED		= 0x80,
};

#endif
