GCOV_PROFILE := y

obj-$(CONFIG_EDP_FRAMEWORK)	+= edp.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= edp_priority.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= sysfs.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= edp_overage.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= edp_fair.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= edp_bestfit.o
obj-$(CONFIG_EDP_FRAMEWORK)	+= edp_temporal.o
