#
# Makefile for IIO Light sensors
#

obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_VCNL4000)		+= vcnl4000.o
obj-$(CONFIG_HID_SENSOR_ALS)	+= hid-sensor-als.o
obj-$(CONFIG_NVS_CM3217)	+= nvs-cm3217.o
nvs-cm3217-objs			+= nvs_cm3217.o
obj-$(CONFIG_NVS_CM3218)	+= nvs-cm3218.o
nvs-cm3218-objs			+= nvs_cm3218.o
obj-$(CONFIG_NVS_MAX4400X)	+= nvs-max4400x.o
nvs-max4400x-objs		+= nvs_max4400x.o

