#
# Makefile for industrial I/O Light sensors
#
GCOV_PROFILE := y

obj-$(CONFIG_SENSORS_CM3218)	+= cm3218.o
obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_SENSORS_ISL29028)	+= isl29028.o
obj-$(CONFIG_TSL2583)	+= tsl2583.o
obj-$(CONFIG_TSL2x7x)	+= tsl2x7x_core.o
obj-$(CONFIG_SENSORS_LTR558)	+= ltr558als.o
obj-$(CONFIG_SENSORS_MAX44005)	+= max44005.o
obj-$(CONFIG_SENSORS_TCS3772)	+= tcs3772.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_TSL2583)		+= tsl2583.o
