#
# Makefile for industrial I/O Light sensors
#

obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_SENSORS_ISL29028)	+= isl29028.o
obj-$(CONFIG_TSL2583)	+= tsl2583.o
obj-$(CONFIG_TSL2x7x)	+= tsl2x7x_core.o
obj-$(CONFIG_SENSORS_LTR558)	+= ltr558als.o
obj-$(CONFIG_SENSORS_MAX44005)	+= max44005.o
