nvshm-objs := nvshm_init.o
nvshm-objs += nvshm_ipc.o
nvshm-objs += nvshm_queue.o
nvshm-objs += nvshm_iobuf.o
nvshm-objs += nvshm_tty.o
nvshm-objs += nvshm_net.o
nvshm-objs += nvshm_if.o

obj-$(CONFIG_NVSHM)		+= nvshm.o

