obj-$(CONFIG_ARCH_TEGRA_18x_SOC)	+= ../../../../kernel-t18x/drivers/firmware/tegra/
obj-$(CONFIG_ARCH_TEGRA_21x_SOC)	+= bpmp_t210.o
obj-$(CONFIG_ARCH_TEGRA_21x_SOC)	+= mail_t210.o
obj-y					+= bpmp.o
obj-y					+= mail.o
obj-y					+= mailman.o
