dtb-$(CONFIG_ARCH_VEXPRESS) += rtsm_ve-aemv8a.dtb foundation-v8.dtb

targets += dtbs
dtb-$(CONFIG_MACH_EXUMA) += tegra132-exuma.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-norrin-pm374-0001-a00-00.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-norrin-pm374-0001-a01-00.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-norrin-tegrasim.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-laguna.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-bowmore-e1973-1000-a01-00.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-bowmore-e1971-1100-a00-00.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-bowmore-e1971-1100-a00-00-pcie.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-bowmore-e1971-1100-a00-00-powerconfig.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-tn8-p1761-1270-a03.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-interposer-e2141-1100-a00-00.dtb
dtb-$(CONFIG_MACH_T132REF) += tegra132-interposer-e2141-1100-a00-00-cboot.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-grenada.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-e2190-1100-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-e2220-1170-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-e2220-1180-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-e2220-1199-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-p2143-1170-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-ers-p2143-1199-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-p2530-0930-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-p2530-0930-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-p2530-0930-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-hdd-p2530-0932-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-hdd-p2530-0932-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-hdd-p2530-0932-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-hdd-rpmb-p2530-0931-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0031-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0031-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0031-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0031-e03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0030-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0030-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0030-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0030-e03-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0131-e00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0131-e01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-p2530-0131-e02-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-vcm30t210.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-vcm30t210.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-vcm31-e2580-0631-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-e2581-0930-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-foster-e-e2581-0930-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0030-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0030-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0031-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0031-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0131-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-loki-e-e2581-0131-a01-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-jetson-e-base-p2595-0000-a00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-jetson-e-p2595-0000-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-hawkeye-p2290-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-hawkeye-p2290-a00-wifi-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_21x_SOC) += tegra210-hawkeye-ffpb-e2295-a00-00.dtb
dtb-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra186-sim-cl33823014.dtb
dtb-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra186-sim-cl34000094.dtb
dtb-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra186-sim-cl34116551.dtb
dtb-$(CONFIG_ARCH_TEGRA_18x_SOC) += tegra186-fpga-cl34078409.dtb
targets += $(dtb-y)

DTC_FLAGS := -i $(srctree)/arch/arm/boot/dts
ifeq ($(CONFIG_ARCH_TEGRA_18x_SOC),y)
DTC_FLAGS += -i $(srctree)/../kernel-t18x/arch/arm64/boot/dts
endif

DTCCPP_FLAGS := -I$(srctree)/arch/arm/boot/dts
ifeq ($(CONFIG_ARCH_TEGRA_18x_SOC),y)
DTCCPP_FLAGS += -I$(srctree)/../kernel-t18x/arch/arm64/boot/dts
endif

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif
targets += $(DTB_LIST)

dtbs: $(addprefix $(obj)/, $(dtb-y))

clean-files := dts/*.dtb *.dtb
