/*
 * Copyright (c) 2013-2014, NVIDIA CORPORATION.  All rights reserved.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _TEGRA_USB_PAD_CTRL_INTERFACE_H_
#define _TEGRA_USB_PAD_CTRL_INTERFACE_H_

#include <mach/xusb.h>

#define UTMIPLL_HW_PWRDN_CFG0			0x52c
#define   UTMIPLL_HW_PWRDN_CFG0_IDDQ_OVERRIDE  (1<<1)
#define   UTMIPLL_HW_PWRDN_CFG0_IDDQ_SWCTL     (1<<0)

#define UTMIP_BIAS_CFG0		0x80c
#define UTMIP_OTGPD			(1 << 11)
#define UTMIP_BIASPD			(1 << 10)
#define UTMIP_HSSQUELCH_LEVEL(x)	(((x) & 0x3) << 0)
#define UTMIP_HSDISCON_LEVEL(x)	(((x) & 0x3) << 2)
#define UTMIP_HSDISCON_LEVEL_MSB	(1 << 24)

#define PCIE_LANES_X4_X1		0
#define PCIE_LANES_X4_X0		2
#define PCIE_LANES_X2_X1		3

/* PCIe/SATA pad phy */
#ifdef CONFIG_ARCH_TEGRA_21x_SOC
#define SS_PAD_COUNT	4
#define USB3_LANE_NOT_ENABLED	0xF
#define SATA_LANE	0x8

#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_0	0x360
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_IDDQ	(1 << 0)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_SLEEP	(0x3 << 1)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_ENABLE	(1 << 3)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_PWR_OVRD	(1 << 4)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_LOCKDET_STATUS	(1 << 15)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_FREQ_MDIV_MASK	(0xF << 16)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_FREQ_NDIV	(25 << 20)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL1_PLL0_FREQ_NDIV_MASK	(0xFF << 20)

#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_0	0x364
#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_PLL0_CAL_EN	(1 << 0)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_PLL0_CAL_DONE	(1 << 1)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_PLL0_CAL_OVRD	(1 << 2)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_CAL_CTRL_MASK	(0xFFFFFF << 4)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL2_PLL0_CAL_CTRL	(0x136 << 4)

#define XUSB_PADCTL_UPHY_PLL_P0_CTL4_0	0x36C
#define XUSB_PADCTL_UPHY_PLL_P0_CTL4_PLL0_REFCLK_SEL_MASK	(0xF << 4)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL4_PLL0_TXCLKREF_SEL	(0x2 << 12)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL4_PLL0_TXCLKREF_SEL_MASK	(0x3 << 12)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL4_PLL0_TXCLKREF_EN	(1 << 15)

#define XUSB_PADCTL_UPHY_PLL_P0_CTL5_0	0x370
#define XUSB_PADCTL_UPHY_PLL_P0_CTL5_DCO_CTRL_MASK	(0xFF << 16)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL5_PLL0_DCO_CTRL	(0x2a << 16)

#define XUSB_PADCTL_UPHY_PLL_P0_CTL8_0	0x37C
#define XUSB_PADCTL_UPHY_PLL_P0_CTL8_PLL0_RCAL_EN	(1 << 12)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL8_PLL0_RCAL_CLK_EN	(1 << 13)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL8_PLL0_RCAL_OVRD	(1 << 15)
#define XUSB_PADCTL_UPHY_PLL_P0_CTL8_PLL0_RCAL_DONE	(1 << 31)

#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2	0x464
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_TX_IDDQ	(1 << 0)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_RX_IDDQ	(1 << 8)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_TX_IDDQ_OVRD	(1 << 1)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_RX_IDDQ_OVRD	(1 << 9)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_TX_SLEEP	(3 << 4)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_RX_SLEEP	(3 << 12)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_TX_PWR_OVRD	(1 << 24)
#define XUSB_PADCTL_UPHY_MISC_PAD_P0_CTL2_RX_PWR_OVRD	(1 << 25)

#define XUSB_PADCTL_UPHY_MISC_PAD_P1_CTL2	0x4A4
#define XUSB_PADCTL_UPHY_MISC_PAD_P2_CTL2	0x4E4
#define XUSB_PADCTL_UPHY_MISC_PAD_P3_CTL2	0x524
#define XUSB_PADCTL_UPHY_MISC_PAD_P4_CTL2	0x564
#define XUSB_PADCTL_UPHY_MISC_PAD_P5_CTL2	0x5A4
#define XUSB_PADCTL_UPHY_MISC_PAD_P6_CTL2	0x5E4
#define XUSB_PADCTL_UPHY_MISC_PAD_S0_CTL2	0x964

#define XUSB_PADCTL_UPHY_PLL_S0_CTL_1_0 0x860
#define XUSB_PADCTL_UPHY_PLL_S0_CTL1_MDIV_MASK	(0x3 << 16)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL1_NDIV_MASK	(0xFF << 20)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL1_PLL0_FREQ_MDIV (0x0 << 16)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL1_PLL0_FREQ_NDIV (0x19 << 20)

#define XUSB_PADCTL_UPHY_PLL_S0_CTL_2_0 0x864
#define XUSB_PADCTL_UPHY_PLL_S0_CTL2_CAL_CTRL_MASK	(0xFFFFFF << 4)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL2_PLL0_CAL_CTRL	(0x136 << 4)

#define XUSB_PADCTL_UPHY_PLL_S0_CTL_4_0 0x86c
#define XUSB_PADCTL_UPHY_PLL_S0_CTL4_TXCLKREF_SEL_MASK	(0x3 << 12)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL4_TXCLKREF_EN_MASK	(0x1 << 15)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL4_PLL0_TXCLKREF_SEL	(0x2 << 12)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL4_PLL0_TXCLKREF_EN	(0x1 << 15)

#define XUSB_PADCTL_UPHY_PLL_S0_CTL_5_0 0x870
#define XUSB_PADCTL_UPHY_PLL_S0_CTL5_DCO_CTRL_MASK	(0xFF << 16)
#define XUSB_PADCTL_UPHY_PLL_S0_CTL5_PLL0_DCO_CTRL	(0x2a << 16)

#else
/* xusb padctl regs for pad programming of t124 usb3 */
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL1_0			0x138
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL1_0_PLL0_REFCLK_NDIV_MASK	(0x3 << 20)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL1_0_PLL0_REFCLK_NDIV	(0x2 << 20)

#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0			0x13c
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_XDIGCLK_SEL_MASK	(0x7 << 0)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_XDIGCLK_SEL		(0x7 << 0)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_TXCLKREF_SEL		(1 << 4)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_TCLKOUT_EN		(1 << 12)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_PLL0_CP_CNTL_MASK	(0xF << 16)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_PLL0_CP_CNTL		(0x8 << 16)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_PLL1_CP_CNTL_MASK	(0xF << 20)
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL2_0_PLL1_CP_CNTL		(0x8 << 20)

#define XUSB_PADCTL_IOPHY_PLL_S0_CTL3_0			0x140
#define XUSB_PADCTL_IOPHY_PLL_S0_CTL3_0_RCAL_BYPASS		(1 << 7)

/* xusb padctl regs for pad programming of pcie */
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL1_0	0x40
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL1_REFCLK_SEL_MASK	(0xF << 12)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL1_REFCLK_SEL	(0x0 << 12)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL1_PLL_RST_		(1 << 1)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL1_PLL0_LOCKDET		(1 << 19)

#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_0	0x44
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_TXCLKREF_SEL	(1 << 4)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_TXCLKREF_EN	(1 << 5)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_REFCLKBUF_EN	(1 << 6)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_PLL0_CP_CNTL_MASK	(0xF << 16)
#define XUSB_PADCTL_IOPHY_PLL_P0_CTL2_PLL0_CP_CNTL_VAL	(0x5 << 16)

#endif

/* PADCTL ELPG_PROGRAM */
#ifdef CONFIG_ARCH_TEGRA_21x_SOC

#define XUSB_PADCTL_ELPG_PROGRAM_0		0x20
#define XUSB_PADCTL_ELPG_PROGRAM_1		0x24
#define SSP0_ELPG_CLAMP_EN			(1 << 0)
#define SSP0_ELPG_CLAMP_EN_EARLY	(1 << 1)
#define SSP0_ELPG_VCORE_DOWN		(1 << 2)
#define SSP1_ELPG_CLAMP_EN			(1 << 3)
#define SSP1_ELPG_CLAMP_EN_EARLY	(1 << 4)
#define SSP1_ELPG_VCORE_DOWN		(1 << 5)
#define SSP2_ELPG_CLAMP_EN			(1 << 6)
#define SSP2_ELPG_CLAMP_EN_EARLY	(1 << 7)
#define SSP2_ELPG_VCORE_DOWN		(1 << 8)
#define SSP3_ELPG_CLAMP_EN			(1 << 9)
#define SSP3_ELPG_CLAMP_EN_EARLY	(1 << 10)
#define SSP3_ELPG_VCORE_DOWN		(1 << 11)
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_CLAMP_EN	(1 << 29)
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_CLAMP_EN_EARLY	(1 << 30)
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_VCORE_DOWN	(1 << 31)

#define USB2_PORT3_WAKE_INTERRUPT_ENABLE	(1 << 3)
#define SS_PORT0_WAKE_INTERRUPT_ENABLE	(1 << 14)
#define SS_PORT1_WAKE_INTERRUPT_ENABLE	(1 << 15)
#define SS_PORT2_WAKE_INTERRUPT_ENABLE	(1 << 16)
#define SS_PORT3_WAKE_INTERRUPT_ENABLE	(1 << 17)

#define SS_PORT0_WAKEUP_EVENT		(1 << 21)
#define SS_PORT1_WAKEUP_EVENT		(1 << 22)
#define SS_PORT2_WAKEUP_EVENT		(1 << 23)
#define SS_PORT3_WAKEUP_EVENT		(1 << 24)

#define USB2_PORT0_WAKEUP_EVENT		(1 << 7)
#define USB2_PORT1_WAKEUP_EVENT		(1 << 8)
#define USB2_PORT2_WAKEUP_EVENT		(1 << 9)
#define USB2_PORT3_WAKEUP_EVENT		(1 << 10)
#define USB2_HSIC_PORT0_WAKEUP_EVENT	(1 << 30)
#define USB2_HSIC_PORT1_WAKEUP_EVENT	(1 << 31)
#define USB2_HSIC_PORT0_WAKE_INTERRUPT_ENABLE	(1 << 28)
#define USB2_HSIC_PORT1_WAKE_INTERRUPT_ENABLE	(1 << 29)

#else
#define XUSB_PADCTL_ELPG_PROGRAM_0		0x1c
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_CLAMP_EN	(1 << 24)
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_CLAMP_EN_EARLY	(1 << 25)
#define XUSB_PADCTL_ELPG_PROGRAM_AUX_MUX_LP0_VCORE_DOWN	(1 << 26)

#define SSP0_ELPG_CLAMP_EN		(1 << 16)
#define SSP0_ELPG_CLAMP_EN_EARLY	(1 << 17)
#define SSP0_ELPG_VCORE_DOWN		(1 << 18)
#define SSP1_ELPG_CLAMP_EN		(1 << 20)
#define SSP1_ELPG_CLAMP_EN_EARLY	(1 << 21)
#define SSP1_ELPG_VCORE_DOWN		(1 << 22)
#define SSP2_ELPG_CLAMP_EN			0x0
#define SSP2_ELPG_CLAMP_EN_EARLY	0x0
#define SSP2_ELPG_VCORE_DOWN		0x0
#define SSP3_ELPG_CLAMP_EN			0x0
#define SSP3_ELPG_CLAMP_EN_EARLY	0x0
#define SSP3_ELPG_VCORE_DOWN		0x0

#define USB2_PORT3_WAKE_INTERRUPT_ENABLE	0x0
#define SS_PORT0_WAKE_INTERRUPT_ENABLE	(1 << 6)
#define SS_PORT1_WAKE_INTERRUPT_ENABLE	(1 << 7)
#define SS_PORT2_WAKE_INTERRUPT_ENABLE	0x0
#define SS_PORT3_WAKE_INTERRUPT_ENABLE	0x0

#define SS_PORT0_WAKEUP_EVENT		(1 << 14)
#define SS_PORT1_WAKEUP_EVENT		(1 << 15)
#define SS_PORT2_WAKEUP_EVENT		0x0
#define SS_PORT3_WAKEUP_EVENT		0x0

#define USB2_PORT0_WAKEUP_EVENT		(1 << 8)
#define USB2_PORT1_WAKEUP_EVENT		(1 << 9)
#define USB2_PORT2_WAKEUP_EVENT		(1 << 10)
#define USB2_PORT3_WAKEUP_EVENT		0x0
#define USB2_HSIC_PORT0_WAKEUP_EVENT	(1 << 11)
#define USB2_HSIC_PORT1_WAKEUP_EVENT	(1 << 12)
#define USB2_HSIC_PORT0_WAKE_INTERRUPT_ENABLE	(1 << 3)
#define USB2_HSIC_PORT1_WAKE_INTERRUPT_ENABLE	(1 << 4)
#endif

/* PADCTL register offset (Shared T124/T210/T114)*/
#define USB2_PORT0_WAKE_INTERRUPT_ENABLE	(1 << 0)
#define USB2_PORT1_WAKE_INTERRUPT_ENABLE	(1 << 1)
#define USB2_PORT2_WAKE_INTERRUPT_ENABLE	(1 << 2)


#define XUSB_PADCTL_USB2_PAD_MUX_0		0x4
#define PAD_PORT_MASK(_p)	(0x3 << (_p * 2))
#define PAD_PORT_SNPS(_p)	(0x0 << (_p * 2))
#define PAD_PORT_XUSB(_p)	(0x1 << (_p * 2))
#define XUSB_DEVICE_MODE	2
#define XUSB_HOST_MODE		1

#define XUSB_PADCTL_USB2_PORT_CAP_0		0x8
#define USB2_OTG_PORT_CAP(_p, val)	((val & 0x3) << (_p * 4))

/* PAD MUX */
#ifdef CONFIG_ARCH_TEGRA_21x_SOC
/* XUSB_PADCTL_USB2_PAD_MUX_0 */
#define BIAS_PAD_MASK	(0x3 << 18)
#define BIAS_PAD_XUSB	(0x1 << 18)
#define HSIC_PAD_TRK	(0x3 << 16)

#define XUSB_PADCTL_USB3_PAD_MUX_0		0x28
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK0	(1 << 1)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK1	(1 << 2)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK2	(1 << 3)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK3	(1 << 4)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK4	(1 << 5)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK5	(1 << 6)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK6	(1 << 7)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_SATA_PAD_IDDQ_DISABLE_MASK0	(1 << 8)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE0	(0x3 << 12)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE1	(0x3 << 14)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE2	(0x3 << 16)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE3	(0x3 << 18)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE4	(0x3 << 20)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE5	(0x3 << 22)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE6	(0x3 << 24)
#define XUSB_PADCTL_USB3_PAD_MUX_SATA_PAD_LANE0	(0x3 << 30)
#define XUSB_PADCTL_USB3_PAD_MUX_SATA_PAD_LANE0_OWNER_USB3_SS	(0x1 << 30)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE0_OWNER_USB3_SS	(0x1 << 12)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE3_OWNER_USB3_SS	(0x1 << 18)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE4_OWNER_USB3_SS	(0x1 << 20)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE5_OWNER_USB3_SS	(0x1 << 22)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE6_OWNER_USB3_SS	(0x1 << 24)
#define PAD_MUX_PAD_LANE(_lane, val)	\
	((_lane == 8) ? ((val & 0x3) << 30) :	\
	((val & 0x3) << (12 + _lane * 2)))
#define PAD_MUX_PAD_LANE_IDDQ(_lane, val)	\
	((_lane == 8) ? ((val & 0x1) << 8) :	\
	((val & 0x1) << (_lane + 1)))

#define XUSB_PADCTL_USB2_BIAS_PAD_CTL_0		0x284
#define XUSB_PADCTL_USB2_BIAS_PAD_CTL_1		0x288
#define PD_MASK			(0x1 << 11)
#define PD				(0x0 << 11)
#define PD_TRK_MASK		(0x1 << 26)
#define PD_TRK			(0x0 << 26)
#define TRK_START_TIMER_MASK		(0x7F << 12)
#define TRK_START_TIMER				(0x1E << 12)
#define TRK_DONE_RESET_TIMER_MASK	(0x7F << 19)
#define TRK_DONE_RESET_TIMER		(0xA << 19)

#define XUSB_PADCTL_HSIC_PAD_TRK_CTL_0		0x340
#define HSIC_TRK_START_TIMER_MASK	(0x7F << 5)
#define HSIC_TRK_DONE_RESET_TIMER_MASK	(0x7F << 12)
#define HSIC_PD_TRK_MASK	(1 << 19)

#define XUSB_PADCTL_HSIC_PAD1_CTL_0_0	0x320
#define PAD1_PD_TX_DATA0		(1 << 1)
#define PAD1_PD_TX_DATA1		(1 << 2)
#define PAD1_PD_TX_STROBE	(1 << 3)
#define PAD1_PD_TX_MASK	\
	(PAD1_PD_TX_DATA0 | PAD1_PD_TX_DATA1 | PAD1_PD_TX_STROBE)


#define XUSB_PADCTL_VBUS_OC_MAP_0	0x18
#define VBUS_OC_MAP(_p, val)	((val & 0xf) << ((_p * 5) + 1))

#define XUSB_PADCTL_OC_DET_0	0x1c
#define VBUS_EN_OC_MAP(x, v)	0x0

#define XUSB_PADCTL_USB2_OTG_PAD_CTL_0(_p)	(0x88 + _p * 0x40)
#define USB2_OTG_HS_CURR_LVL	(0x3F << 0)
#define USB2_OTG_PD		(0x1 << 26)
#define USB2_OTG_PD2	(0x1 << 27)
#define USB2_OTG_PD_ZI	(0x1 << 29)

#define XUSB_PADCTL_USB2_OTG_PAD_CTL_1(_p)	(0x8c + _p * 0x40)
#define USB2_OTG_TERM_RANGE_ADJ	(0xF << 3)
#define USB2_OTG_PD_DR			(0x1 << 2)
#define RPD_CTRL				(0x1f << 26)
#define USB2_OTG_HS_IREF_CAP			0x0
#define USB2_OTG_PD_CHRP_FORCE_POWERUP	0x0
#define USB2_OTG_PD_DISC_FORCE_POWERUP	0x0

#define XUSB_PADCTL_USB2_BATTERY_CHRG_OTGPAD_CTL1(_p)	\
	(0x84 + _p * 0x40)
#define VREG_FIX18	(1 << 6)
#define VREG_LEV	(0x3 << 7)
#define VREG_LEV_EN	(0x1 << 7)

#define XUSB_PADCTL_USB2_OC_MAP_0	0x10
#define PORT_OC_PIN(_p, val)	((val & 0xf) << (_p * 4))
#define OC_VBUS_PAD(p)	(p + 4)
#define OC_DISABLED	0xf

#define XUSB_PADCTL_SS_PORT_MAP	0x14
#define SS_PORT_MAP(_p, val) \
	((val & 0x7) << (_p * 5))

#define XUSB_PADCTL_USB2_VBUS_ID_0	0xc60
#define VBUS_SOURCE_SELECT(val)	((val & 0x3) << 12)
#define ID_SOURCE_SELECT(val)	((val & 0x3) << 16)
#define IDDIG_CHNG_INTR_EN		(1 << 11)

#else
#define XUSB_PADCTL_USB3_PAD_MUX_0		0x134
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK0	(1 << 1)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK1	(1 << 2)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK2	(1 << 3)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK3	(1 << 4)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_PCIE_PAD_IDDQ_DISABLE_MASK4	(1 << 5)
#define XUSB_PADCTL_USB3_PAD_MUX_FORCE_SATA_PAD_IDDQ_DISABLE_MASK0	(1 << 6)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE0	(0x3 << 16)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE1	(0x3 << 18)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE2	(0x3 << 20)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE3	(0x3 << 22)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE4	(0x3 << 24)
#define XUSB_PADCTL_USB3_PAD_MUX_SATA_PAD_LANE0	(0x3 << 26)
#define XUSB_PADCTL_USB3_PAD_MUX_SATA_PAD_LANE0_OWNER_USB3_SS	(0x1 << 26)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE0_OWNER_USB3_SS	(0x1 << 16)
#define XUSB_PADCTL_USB3_PAD_MUX_PCIE_PAD_LANE1_OWNER_USB3_SS	(0x1 << 18)

#ifdef CONFIG_ARCH_TEGRA_11x_SOC
#define XUSB_PADCTL_USB2_BIAS_PAD_CTL_0		0xa0
#else
#define XUSB_PADCTL_USB2_BIAS_PAD_CTL_0		0xb8
#endif
#define PD_MASK		(0x1 << 12)

#define XUSB_PADCTL_VBUS_OC_MAP_0	0x0
#define VBUS_OC_MAP(_p, val)	0x0

#define XUSB_PADCTL_OC_DET_0	0x18
#define VBUS_EN_OC_MAP(x, v) \
	(((x) == 2) ? \
	(((v) & 0x7) << 5) : (((v) & 0x7) << (10 + 3 * (x))))

#define XUSB_PADCTL_USB2_OTG_PAD_CTL_0(_p)	(0xa0 + _p * 0x4)
#define USB2_OTG_HS_CURR_LVL	(0x3F << 0)
#define USB2_OTG_PD				(0x1 << 19)
#define USB2_OTG_PD2			(0x1 << 20)
#define USB2_OTG_PD_ZI			(0x1 << 21)

#define XUSB_PADCTL_USB2_OTG_PAD_CTL_1(_p)	(0xac + _p * 0x4)
#define USB2_OTG_PD_DR					(0x1 << 2)
#define USB2_OTG_TERM_RANGE_ADJ			(0xF << 3)
#define USB2_OTG_HS_IREF_CAP			(0x3 << 9)
#define USB2_OTG_PD_CHRP_FORCE_POWERUP	(0x1 << 0)
#define USB2_OTG_PD_DISC_FORCE_POWERUP	(0x1 << 1)
#define RPD_CTRL						0x0

#define XUSB_PADCTL_USB2_OC_MAP_0	0x10
#define PORT_OC_PIN(_p, val)	((val & 0xf) << (_p * 3))
#define OC_VBUS_PAD(p)	(p + 4)
#define OC_DISABLED	0xf

#define XUSB_PADCTL_SS_PORT_MAP	0x14
#define SS_PORT_MAP(_p, val) \
	((val & 0x7) << (_p * 4))

#define XUSB_PADCTL_USB2_BATTERY_CHRG_OTGPAD_CTL1(_p)	0x0
#define VREG_FIX18	0x0
#define VREG_LEV	0x0
#define VREG_LEV_EN	0x0
#define RPD_CTRL	0x0

#define XUSB_PADCTL_USB2_VBUS_ID_0	0x0
#define VBUS_SOURCE_SELECT(val)	0x0
#define ID_SOURCE_SELECT(val)	0x0
#define IDDIG_CHNG_INTR_EN		0x0

#define HSIC_PAD_TRK	0x0
#define TRK_START_TIMER_MASK		0x0
#define TRK_DONE_RESET_TIMER_MASK	0x0

#define XUSB_PADCTL_HSIC_PAD_TRK_CTL_0	0x0
#define HSIC_TRK_START_TIMER_MASK		0x0
#define HSIC_TRK_DONE_RESET_TIMER_MASK	0x0
#define HSIC_PD_TRK_MASK	0x0

#define XUSB_PADCTL_HSIC_PAD1_CTL_0_0	0x0
#define PAD1_PD_TX_MASK	0x0
#endif
/* SATA PADPLL */
#define CLK_RST_CONTROLLER_SATA_PLL_CFG0_0	0x490
#define SATA_PADPLL_USE_LOCKDET			(1 << 2)
#define SATA_PADPLL_RESET_SWCTL			(1 << 0)
#define SATA_SEQ_ENABLE				(1 << 24)
#define SATA_SEQ_START_STATE			(1 << 25)

#define CLK_RST_CONTROLLER_XUSBIO_PLL_CFG0_0		0x51C
#define XUSBIO_PADPLL_RESET_SWCTL			(1 << 0)
#define XUSBIO_CLK_ENABLE_SWCTL			(1 << 2)
#define XUSBIO_PADPLL_USE_LOCKDET			(1 << 6)
#define XUSBIO_PADPLL_SLEEP_IDDQ			(1 << 13)
#define XUSBIO_SEQ_ENABLE				(1 << 24)

void tegra_xhci_release_otg_port(bool release);
void tegra_xhci_release_dev_port(bool release);
void tegra_xhci_ss_wake_on_interrupts(u32 portmap, bool enable);
void tegra_xhci_hs_wake_on_interrupts(u32 portmap, bool enable);
void tegra_xhci_ss_wake_signal(u32 portmap, bool enable);
void tegra_xhci_ss_vcore(u32 portmap, bool enable);

int utmi_phy_pad_disable(void);
int utmi_phy_pad_enable(void);
int usb3_phy_pad_enable(u32 lane_owner);
int pcie_phy_pad_enable(bool enable, int lane_owner);

int utmi_phy_iddq_override(bool set);
void tegra_usb_pad_reg_update(u32 reg_offset, u32 mask, u32 val);
u32 tegra_usb_pad_reg_read(u32 reg_offset);
void tegra_usb_pad_reg_write(u32 reg_offset, u32 val);

void xusb_utmi_pad_init(int pad, u32 cap, bool external_pmic);
void xusb_ss_pad_init(int pad, int port_map, u32 cap);
void usb2_vbus_id_init(void);
int hsic_trk_enable(void);

#endif
