GCOV_PROFILE := y

subdir-ccflags-y	+= -Werror
lib-y		:= bitops.o delay.o clear_user.o			\
		   copy_from_user.o copy_to_user.o copy_in_user.o	\
		   copy_page.o clear_page.o				\
		   memchr.o memmove.o memset.o				\
		   strchr.o strrchr.o					\
		   memcpy.o
